### ISSUE TITLE
Nil returned when using green wire

### ISSUE THREAD

**Issue by vedymin** [LuziferSenpai/Automatic-Coupling-System#1]
Second if in function CS return r instead of g (line 20)

**Comment by vedymin** [comment]
I don't know why it is not referenced, but this is in control.lua file

**Comment by robot256** [comment]
Any idea when you'll be able to patch the version on the mod portal?  It works perfectly with that one character fixed.

**Comment by LuziferSenpai** [comment]
Fixed in next Version, will be released when Internet is back up
