### ISSUE TITLE
Automatic-Coupling-System 

### ISSUE THREAD

**Issue by Jeffstan123** [LuziferSenpai/Automatic-Coupling-System#3]
i cannot get trains to couple to a row of cargo wagons. It will either pick up no wagons or just one wagon.

**Comment by LuziferSenpai** [comment]
Did you read the Description?
Followed you the Description?

**Comment by Jeffstan123** [comment]
Yes I did. I figure it out. I had a weird spacing between the wagons and my engine. After fixing this it worked flawlessly
