### ISSUE TITLE
Smart Trains Support

### ISSUE THREAD

**Issue by MrDrummer** [LuziferSenpai/Automatic-Coupling-System#4]
I absolutely love this mod.

I use it for multiple systems including dropping off a long haul of wagons at an outpost, then when they are full / empty, the next train comes with a set of wagons and swaps them.

Only issue with this is that the trains lose their Smart Train route (thus not following the "go to x station" logic) when they (de)couple, I am assuming because it changes the train ID.

I was wondering that if there is support for it, hook into the Smart Trains API as an optional dependency, and update the train's ID, or even better, keep the train's ID when it (de)couples? if that is even possible.

Thanks in advance :)

**Comment by LuziferSenpai** [comment]
Currently working on it, but without the Dev of Smarter Trains this will not work, so I'm contacting him.

**Comment by LuziferSenpai** [comment]
Because Choumiko didnt replied in the last Weeks, I now released my Version of controlling Trains, it was a Part from one of my older Mods. A Example how it could be used is included. Feel free to test it ;) https://mods.factorio.com/mod/Simple_Circuit_Trains
