### ISSUE TITLE
Migration error loading 0.2.3 save with 0.2.4

### ISSUE THREAD

**Issue by robot256** [LuziferSenpai/Automatic-Coupling-System#5]
Loading one of my old saves which was created with ACS version 0.2.3 with the latest version, I get the following error:

Error while running event Automatic_Coupling_System::on_configuration_changed
LuaEntity doesn't contain key s.
stack traceback:
	__Automatic_Coupling_System__/control.lua:228: in function <__Automatic_Coupling_System__/control.lua:208>
stack traceback:
	[C]: in function '__index'
	__Automatic_Coupling_System__/control.lua:228: in function <__Automatic_Coupling_System__/control.lua:208>

Only way I could get it to run was by commenting out the table migration code completely.

Full log and save file attached.
[factorio-current.log](https://github.com/LuziferSenpai/Automatic-Coupling-System/files/3992111/factorio-current.log)
[rail 1k_Dispatcher_v66_alternate.zip](https://github.com/LuziferSenpai/Automatic-Coupling-System/files/3992112/rail.1k_Dispatcher_v66_alternate.zip)

**Comment by LuziferSenpai** [comment]
Yea, will look into it, it seems something went wrong inside 0.2.3, so yea, because in my testing this all worked fine.

**Comment by LuziferSenpai** [comment]
I need your mods folder, so I dont crash anything.

**Comment by robot256** [comment]
Here is the mods folder that reproduces the problem: https://drive.google.com/file/d/1kacftAF-L0WQxT4O-vSqQjdn2wagNx6R/view?usp=sharing

**Comment by LuziferSenpai** [comment]
So, I found the Problem now, BUT its nothing I can fix, because you somehow got Data from 0.2.2 in your File, so sry, but you need to remove the mod, load the savegame, save it, and then enable the mod again. Sry for this!

**Comment by robot256** [comment]
Okay, thanks for checking!  Don't know how that happened.  It did load and save after removing the migration code, so if it's still broken I will try disabling the mod.
